language: csharp
solution: CSharpSampleProject.sln

install:
  - nuget restore CSharpSampleProject.sln
  - nuget install NUnit.Console -Version 3.8.0 -OutputDirectory testrunner

  script:
  - xbuild /p:Configuration=Release CSharpSampleProject.sln
  - mono ./testrunner/NUnit.Runners.3.8.0/tools/nunit-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll