language: csharp
solution: AtlantisDotNet.sln

install:
  - nuget restore AtlantisDotNet.sln
  - nuget install NUnit.Console -Version 3.8.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release AtlantisDotNet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Atlantis.UserData.DAL.Tests/bin/Release/Atlantis.UserData.DAL.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Atlantis.RawMetrics.DAL.Tests/bin/Release/Atlantis.RawMetrics.DAL.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./RawMetrics.API.Tests/bin/Release/RawMetrics.API.Tests.dll