//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlantis.UserData.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public int DeviceTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
        public virtual User User { get; set; }
    }
}
